// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_buggy : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Steering
        {
            get
            {
                return Valve.VR.SteamVR_Input.__actions_buggy_in_Steering;
            }
        }
        
        public virtual SteamVR_Action_Single Throttle
        {
            get
            {
                return Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle;
            }
        }
        
        public virtual SteamVR_Action_Boolean Brake
        {
            get
            {
                return Valve.VR.SteamVR_Input.__actions_buggy_in_Brake;
            }
        }
        
        public virtual SteamVR_Action_Boolean Reset
        {
            get
            {
                return Valve.VR.SteamVR_Input.__actions_buggy_in_Reset;
            }
        }
    }
}
